#!/usr/bin/env bash
shopt -s nullglob globstar

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

dmenu=${PASSMENU_DMENU:-dmenu}
xdotool=${PASSMENU_XDOTOOL:-xdotool type --clearmodifiers --file -}

otp=0
if [[ $1 == "--otp" ]]; then
	otp=1
	shift
fi

password=$(printf '%s\n' "${password_files[@]}" | $dmenu)
[[ -n $password ]] || exit

if [[ $otp -eq 0 ]]; then
	pass show "$password" | head -n1 | tr -d '\n' | $xdotool
else
	pass otp code "$password" | head -n1 | tr -d '\n' | $xdotool
fi
